export enum MsgWarning {
  power = 'Battery Low',
  temp = 'Over Temperature',
  x_rms_ACC_mg = 'X over value',
  x_max_ACC_mg = 'X over value',
  x_velocity_mm_sec = 'X over value',
  x_displacement_mm = 'X over value',
  x_peak_one_Hz = 'X over value',
  x_peak_two_Hz = 'X over value',
  x_peak_three_Hz = 'X over value',
  y_rms_ACC_mg = 'Y over value',
  y_max_ACC_mg = 'Y over value',
  y_velocity_mm_sec = 'Y over value',
  y_displacement_mm = 'Y over value',
  y_peak_one_Hz = 'Y over value',
  y_peak_two_Hz = 'Y over value',
  y_peak_three_Hz = 'Y over value',
  z_rms_ACC_mg = 'Z over value',
  z_max_ACC_mg = 'Z over value',
  z_velocity_mm_sec = 'Z over value',
  z_displacement_mm = 'Z over value',
  z_peak_one_Hz = 'Z over value',
  z_peak_two_Hz = 'Z over value',
  z_peak_three_Hz = 'Z over value',
}

export const titleWarning = 'Hệ thống giám sát động cơ điện cảnh báo';
